### ISSUE TITLE
Automate sirepo alpha builds

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#10]
Sirepo image builds happen nightly. Ideally, push to alpha automatically. Eventually, run test suite.

Would like to have build machine use Salt to manage the builds and pushes. This may add too
much complexity right now.

Don't want automatic checkin builds, because state may be inconsistent on build (e.g. SRW not updated simultaneously). Nightly seems good compromise.

**Comment by mrakitin** [comment]
+1 for nightly builds in case we have commits.

**Comment by robnagler** [comment]
We are building automatically now. We aren't deploying automatically, and probably won't need to for some time.
