### ISSUE TITLE
Create announcement for OPAL list

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#106]
Andreas wants to announce our jupyter server.

**Comment by robnagler** [comment]
How about this? @bruhwiler @pmessamer

RadiaSoft has added OPAL to our suite of beam simulation tools available instantly via your browser for free:

https://jupyter.radiasoft.org

You can run OPAL via the command line or with [pyOPALTools](https://gitlab.psi.ch/OPAL/pyOPALTools) in an IPython notebook.

All you need is a a [GitHub account](https://github.com) to login to our Jupyter server.​

Along with OPAL, the following codes come pre-installed on jupyter.radiasoft.org: 
Elegant, Genesis, Hellweg, Shadow, SRW, Synergia, and WARP.

​Our cloud computing infrastructure is completely open source, from the Python server to the JavaScript user interfaces:

https://github.com/radiasoft

Our Jupyter server runs inside [Docker containers](https://www.docker.com/), which enable immediate access to all the scientific codes above. You can download our Docker images here:

https://hub.docker.com/u/radiasoft

Our [Vagrant images](https://www.vagrantup.com/) make it possible to run scientific codes that require X11 directly on Mac and PC computers, using [VirtualBox](https://www.virtualbox.org/). These are also freely available:

https://app.vagrantup.com/radiasoft

If you have any questions, please contact us at support@radiasoft.net.

**Comment by messamer** [comment]
Suggest noodling with this sentence: "Along with OPAL, the following codes come pre-installed on jupyter.radiasoft.org: Elegant, Genesis, Hellweg, Shadow, SRW, Synergia, and WARP."  Maybe "OPAL is the newest addition to our suite of preinstalled codes on jupyter.radiasoft.org.  We now support OPAL, Elegant, Genesis, Hellweg, Shadow, SRW, Synergia, and WARP."

In what context does this appear? For what audience?  Should we say something about OPAL?

Would you like a formal announcement as a PDF? What is Andreas' need?
Paula

**Comment by robnagler** [comment]
Sent text to Andreas
