### ISSUE TITLE
Install Radiasoft-warp branch for use on Sirepo

### ISSUE THREAD

**Issue by ncook882** [radiasoft/devops#109]
The newest features of the Warp-VND interface for Sirepo require [Radiasoft-warp](https://bitbucket.org/radiasoft/warp) to be installed.

**Comment by robnagler** [comment]
We were already building off our fork but with an older commit. I changed to "master". I started a build, and will let you know when this is on jupyter.

**Comment by robnagler** [comment]
The Jupyter server has been updated (see below). To upgrade warp on your VM:

```
curl radia.run | bash -s code warp
```

Here's the manifest for Warp:

```json
            "warp": {
                "installed": "2017-09-11T19:58:32Z",
                "name": "warp",
                "source_d": "/home/vagrant/src/radiasoft/codes/warp-20170911.195802/warp",
                "uri": "https://bitbucket.org/radiasoft/warp.git",
                "version": "81e4e142f15825dda4fc2baf3778af0912ddbd5f"
            },
```
