### ISSUE TITLE
Configure VM for BNL

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#110]
@mrakitin: Create an rsconf configuration for BNL. Need to consider flask http vs nginx/uwsgi. Run by external proxy. Will run on VirtualBox/Vagrant.

**Comment by mrakitin** [comment]
Thanks Rob!

**Comment by robnagler** [comment]
@mrakitin is this still an issue?

**Comment by mrakitin** [comment]
I think https://github.com/radiasoft/sirepo/wiki/Development covers the instructions, so It's not an issue.

**Comment by mrakitin** [comment]
Forgot to ask - are there services configured in that box? I remembered the original idea was to have an independent box with Sirepo services started automatically on system boot.
