### ISSUE TITLE
Rebuild Synergia for beamsim

### ISSUE THREAD

**Issue by ncook882** [radiasoft/devops#124]
The most recent commit [e6e6bc91](https://cdcvs.fnal.gov/redmine/projects/synergia2/repository/revisions/e6e6bc9151eeee465f10be1576efd16ad0dce933) to the Synergia2 development branch fixes an inconsistency with the stepper construction algorithm which has been preventing me from loading certain lattice files. I've been running Synergia on the container both locally and on Jupyter, so it would be great if this newest fix could be incorporated.

**Comment by robnagler** [comment]
Starting a build.

**Comment by robnagler** [comment]
Loaded on jupyter.radiasoft.org

**Comment by ncook882** [comment]
Hi Rob. I'm still seeing this issue on jupyter.radiasoft.org. I've logged out and restarted my server several times. Is it possible that the Synergia build is using a different brach or is not up-to-date?

**Comment by robnagler** [comment]
It's using the default branch, which I'm pretty sure is devel.

We keep a mirror of the FNL repos, because their server times out so frequently. I suspect that the commit came after the mirror happened. I'll rebuild.

**Comment by robnagler** [comment]
The new image is on jupyter.radiasoft. I checked the build, and it seems to be right. 

Let me know if there are issues.
