### ISSUE TITLE
Amend rsmanifest for Synergia version in containers

### ISSUE THREAD

**Issue by ncook882** [radiasoft/devops#127]
Currently the manifest for the containers documents the [contract-synergia2](https://cdcvs.fnal.gov/redmine/projects/contract-synergia2/repository?utf8=%E2%9C%93&rev=devel) repository. Although this may be the repository needed for properly building the code, it obscures actual information about the current Synergia version/commit. 

Would it be possible to change the manifest to provide the [Synergia2](https://cdcvs.fnal.gov/redmine/projects/synergia2/repository?utf8=%E2%9C%93&rev=devel) commit information for the installed code?

**Comment by robnagler** [comment]
Yes, we should do this.
