### ISSUE TITLE
mpi requires cap_ptrace or printing a message now

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#132]
Latest image running warp or elegant with mpiexec produces errors of the form:

```text
[v4.radia.run:00192] Read -1, expected 10024, errno = 1
```
The results of the simulation seem to be correct, but there are a lot of errors output.

Running the container with `--cap-add=SYS_PTRACE` removes the errors. Running strace on the mpiexec shows that [set_robust_list](https://linux.die.net/man/2/set_robust_list) is called, which is like one of the capabilities enabled with by [CAP_SYS_PTRACE](http://man7.org/linux/man-pages/man7/capabilities.7.html):

* Trace arbitrary processes using ptrace(2);
* apply get_robust_list(2) to arbitrary processes;
* transfer data to or from the memory of arbitrary processes using process_vm_writev(2);
* inspect processes using kcmp(2).

It may be that the problem is that openmpi is printing an error that was happening all along, or it may be that mpi is trying to use futexes for the first time. It does happen with elegant, which also seems to produce correct results.

**Comment by robnagler** [comment]
@moellep did some digging and found [this line](https://github.com/open-mpi/ompi/blob/9c3ae64297e034b30cb65298908014764216c616/opal/mca/btl/vader/btl_vader_get.c#L76), which causes the error:

```c
opal_output(0, "Read %ld, expected %lu, errno = %d\n", (long)ret, (unsigned long)size, errno);
```

Reported in open-mpi/ompi#3270. 

In order to use CMA, which is faster shared memory, we have to enable ptrace in the container. It's not clear what the issues are with this in Jupyter. 

I think this brings the larger issue of switching to Singularity or Charlie Cloud to run MPI jobs. We shouldn't let people run MPI from Jupyter directly but instead force them to queue on the cluster.

For now, I will look at disabling CMA in MPI from the environment to avoid this error message.

**Comment by robnagler** [comment]
@cchall The solution for the short term is to explicitly set "sm" (shared memory) instead of letting mpi to try vader/cma, so in your example:

```sh
mpiexec --mca btl self,sm -n 2 python me_plates.py
```

**Comment by robnagler** [comment]
@cchall @j-edelen Please test again by stopping and starting your container.

The home environment now sets `OMPI_MCA_blt=self,sm,tcp` if the shell is running in a docker container. If you stop and start your container, it will automatically update the environment with this value. It won't work inside a notebook just yet (build required, which is happening), but it will work in a terminal.

Thanks for your patience.

**Comment by j-edelen** [comment]
@robnagler I am running opal now and everything seems to be working as expected.

**Comment by robnagler** [comment]
Deployed on alpha.sirepo and jupyter2.
