### ISSUE TITLE
radiasoft.net/open-source not found

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#137]
This link is in all of our README.md files.

**Comment by robnagler** [comment]
@messamer will you have a look? (I can't assign you for some reason.)

**Comment by messamer** [comment]
Hi Rob-

What should I look at?  I cannot magically cause a server error...

P

**Comment by robnagler** [comment]
radiasoft.net/open-source is no longer pointing at a valid page. I'm not sure what it was before, but it's a link we had. You need to redirect this link to the appropriate page for open source documentation. Here's an example usage: https://github.com/radiasoft/sirepo#license

**Comment by messamer** [comment]
fixed-  redirected radiasoft.net/open-source to  radiasoft.net/products
<http://radiasoft.net/open-source>

**Comment by bruhwiler** [comment]
An "Open Source" link appeared along the top of the website.
I fixed it.
