### ISSUE TITLE
radiasoft.net  WordPress wants PHP update

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/devops#138]
Your site could be faster and more secure with a newer PHP version.

Hey, we've noticed that you're running an outdated version of PHP. PHP is the programming language that WordPress and Yoast SEO are built on. The version that is currently used for your site is no longer supported. Newer versions of PHP are both faster and more secure. In fact, your version of PHP no longer receives security updates, which is why we're sending you to this notice.

Hosts have the ability to update your PHP version, but sometimes they don't dare to do that because they're afraid they'll break your site.

To which version should I update?

You should update your PHP version to either 5.6 or to 7.0 or 7.1. On a normal WordPress site, switching to PHP 5.6 should never cause issues. We would however actually recommend you switch to PHP7. There are some plugins that are not ready for PHP7 though, so do some testing first. We have an article on how to test whether that's an option for you here. PHP7 is much faster than PHP 5.6. It's also the only PHP version still in active development and therefore the better option for your site in the long run.

**Comment by robnagler** [comment]
All part of the plan. :)

**Comment by robnagler** [comment]
Done
