### ISSUE TITLE
beta backend crashing

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#150]
The beta.sirepo.com front end is working, but all simulation reports are failing with a bad gateway. fnl5b logs show "socket.error: [Errno 104] Connection reset by peer".

Running update-beta.sh on fnl1 didn't correct the problem.

**Comment by moellep** [comment]
Also, noticed this in the fnl5 celery_sirepo logs:

Jun 18 19:06:36 fnl5b.bivio.biz celery_sirepo[29163]: [2018-06-18 19:06:36,486: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-b
eta.sirepo.com:5672//: [Errno 104] Connection reset by peer.

**Comment by moellep** [comment]
Restarted back-end processes and Rob fixed core dump size and it is running again.

**Comment by robnagler** [comment]
out of disk space caused by core dumps (biviosoftware/devops#200). No longer will core dump

We have a specific simulation which was causing the core dumps, and @moellep is debugging.
