### ISSUE TITLE
comsol server license unavailable - no processes running

### ISSUE THREAD

**Issue by nickgoldring** [radiasoft/devops#151]
When opening an application from the COMSOL server application library, I receive the error message that the maximum number of users is already reached even though there are no other users logged on. Additionally there are no other simulations running.

I was running applications on the server throughout the day today without any problems.

![image](https://user-images.githubusercontent.com/32494032/41758204-6a22e4e4-75a4-11e8-87eb-8831f3f43b52.png)

![image](https://user-images.githubusercontent.com/32494032/41758260-b4b67afc-75a4-11e8-956b-b115d4b68ba2.png)

**Comment by robnagler** [comment]
Looks like the disk is full

**Comment by robnagler** [comment]
/tmp was 2.9g. There were a bunch of csbatchNNN directories in there. I'll see if there's a way to tell COMSOL to not use /tmp.

**Comment by robnagler** [comment]
Please test now, because disk is back to normal.

**Comment by robnagler** [comment]
There's [no way to change systemd's tmpdir](https://unix.stackexchange.com/questions/435367/is-it-possible-to-change-systemd-private-tmp-directory), which would be the obvious fix. There is a concept of PrivateTmp, but it binds /tmp in the service to a subdirectory in /tmp. 

Already passing -tmpdir to comsol, but it seems that this [has been broken for almost a decade](https://www.comsol.com/forum/thread/12209/change-the-directory-of-temporary-file). 

I'll try setting $tmp and $TMPDIR, but I doubt this will work.

**Comment by nickgoldring** [comment]
I'm still getting the license error message, unfortunately. I created an account for Jason Lerch (APS) and he was experiencing the same problem this morning. 

I built some models recently that are supposed to run simultaneous iterations of the same computation over all available cores - the full solution is found by summing over the results of each iterative solution which need to be stored somewhere.  This process must have filled the disk - there are many options to play with on my end that could help to mitigate this problem. I'll message you offline about those.

Thanks.

**Comment by robnagler** [comment]
I suspect we have some type of runaway process situation. LMK if I should just reboot the server:

```text
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 3637 comsol    20   0 11.139g 4.121g  51356 R 100.3  1.1   1098:31 comsollauncher
 3638 comsol    20   0 10.305g 3.387g  51592 S 100.0  0.9   1098:53 comsollauncher
29133 comsol    20   0 9143192 809944  36524 R 100.0  0.2   9983:19 comsollauncher
29134 comsol    20   0 8912980 851784  37232 S 100.0  0.2   9983:43 comsollauncher
29135 comsol    20   0 8913148 864448  37232 S 100.0  0.2   9984:44 comsollauncher
29136 comsol    20   0 8913140 896848  36976 S 100.0  0.2   9984:58 comsollauncher
```

**Comment by nickgoldring** [comment]
Okay. Yes, please reboot the server.

**Comment by robnagler** [comment]
Rebooted. Would your run a batch job so I can see if it is putting files in a different tmp directory?

**Comment by nickgoldring** [comment]
Absolutely. I'm uploading a new version now and will run it within a few minutes.

**Comment by robnagler** [comment]
There's now a /srv/comsol/start which does a bind mount of /srv/comsol/tmp to /tmp and then a sudo to comsol to run the server. This should prevent access to /tmp
