### ISSUE TITLE
linking errors when building JSPEC 

### ISSUE THREAD

**Issue by ilyapogorelov** [radiasoft/devops#156]
For development of new features, I'll need to repeatedly re-build the JSPEC code (the JLab cooling code).  The code relies on the muparser library for parsing the math expressions in input files.  I'm getting errors at the linking stage as I try to build the code on macos and on Linux at NERSC.  I've tried different approaches (compiling the library in to .a or .so, combining the library source with the code source proper, linking the object files separately, etc), without success.  I get different error messages for different approaches.  

I know JSPEC was built successfully for running through sirepo, so any help/advise you could provide on building the code would be hugely helpful.  Thanks!

**Comment by robnagler** [comment]
You can find out how we build any code by looking in this directory: https://github.com/radiasoft/download/blob/master/installers/code/codes

For jspec, it's this file: https://github.com/radiasoft/download/blob/master/installers/code/codes/jspec.sh

It doesn't do anything special. We use the muParser-devel-2.2.5-5.fc27.x86_64 package from Fedora 27. What system are you building on?

**Comment by robnagler** [comment]
It would help to have the error messages, build script, etc.

Alternatively, you might consider using the VM. I can't remember. Did we set one up for you?
