### ISSUE TITLE
Configure MPI on fnl11 mounting from fnl15

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#179]
@zhigangwu2018 needs another node for ALE3D. fnl11 is similarly configured to fnl15. 

- [x] Mount his home directory from fnl15 on fnl11.
- [x] Setup ssh keys and MPI hosts file
- [x] Ensure fnl11 packages are same as fnl15

**Comment by robnagler** [comment]
@zhigangwu2018 you can run mpi this way:

```sh
mpiexec --hostfile ~/mpihosts -n 32 <your command>
```

Your home directory is mounted on the other host (fnl11b).

Let me know if you have questions.

**Comment by zhigangwu2018** [comment]
Thanks!
