### ISSUE TITLE
jupyter stop/start server shows confusing message

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#182]
When you are in a browser on the jupyter page, and select "Hub / Control Panel" it opens in a new tab. Selecting Stop My Server and the Start My Server on that page then shows the error message:

![Screen Shot 2019-06-12 at 2 50 21 PM](https://user-images.githubusercontent.com/6516910/59385377-6c2f7f00-8d21-11e9-8569-8a6d2f529ba1.png)

Closing the old juptyer tab before stop/start and the problem doesn't occur.

If possible, the "Hub / Control Panel" shouldn't open a new browser window, but should stay on the same page.

**Comment by robnagler** [comment]
That's been fixed in JupyterLab 1.0 which will be coming out next week. I don't want to install the alpha version so just type anything for now

**Comment by robnagler** [comment]
Fixed in JupyterLab 1.x
