### ISSUE TITLE
rsmpi not working

### ISSUE THREAD

**Issue by JohanCar1sson** [radiasoft/devops#183]
CapLaserBELLA-001$ hostname
rs14.local
CapLaserBELLA-001$ rsmpi -n 8 python2 flash4
bash: orted: command not found
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
bash: orted: command not found

**Comment by robnagler** [comment]
You need to restart your server. It is still running the old image. Please let me know if rsmpi works after that.

**Comment by JohanCar1sson** [comment]
How do I restart the server? Logging out from jupyter and logging back in didn't do it.

**Comment by bruhwiler** [comment]
You want to open the hub control panel and see something like the following:

![image](https://user-images.githubusercontent.com/3825435/62792939-98e7e480-ba8d-11e9-89f0-4cdf13670939.png)

Press 'stop server' and then you'll be able to restart.

It's funny, because I restarted my server and now the UI is quite different.
Getting to the hub control panel requires a different workflow.

**Comment by JohanCar1sson** [comment]
OK, found it! It's "File" -> "Hub Control Panel". Not sure what "hub" that is, but it had the bright magic button I needed!

**Comment by JohanCar1sson** [comment]
At least I get a different MPI error now!

CapLaserBELLA-001$ rsmpi -n 8 python2 flash4
[mpiexec@rs14.local] match_arg (utils/args/args.c:159): unrecognized argument mca
[mpiexec@rs14.local] HYDU_parse_array (utils/args/args.c:174): argument matching returned error
[mpiexec@rs14.local] parse_args (ui/mpich/utils.c:1596): error parsing input array
[mpiexec@rs14.local] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1648): unable to parse user arguments
[mpiexec@rs14.local] main (ui/mpich/mpiexec.c:149): error parsing parameters
CapLaserBELLA-001$

**Comment by robnagler** [comment]
You need to recompile flash with mpich. [See recent release notes](https://github.com/radiasoft/jupyter.radiasoft.org/issues/50)

**Comment by robnagler** [comment]
> It's "File" -> "Hub Control Panel"

This was a discussion topic at the recent Jupyter workshop. I think it's in the wrong place...

**Comment by JohanCar1sson** [comment]
But I'm still using Flash 4.5. Why did OpenMPI mpiexec stop working?

**Comment by robnagler** [comment]
Please see https://github.com/radiasoft/sirepo/issues/1750  

I believe Flash supports MPICH. At least they say they do.

**Comment by JohanCar1sson** [comment]
Alright, I'll try Flash 4.6.1 built w/ MPICH. Thanks!

**Comment by ncook882** [comment]
Let me know how this goes @JohanCar1sson . I'm planning to upgrade to Flash 4.6.1 shortly. It has some potentially valuable improvements to computing magnetic resistivity at lower densities.

**Comment by robnagler** [comment]
I don't know if you know this, but HYPRE 2.11 is [built into the server](https://github.com/radiasoft/container-beamsim). This should save you time compiling FLASH.

**Comment by JohanCar1sson** [comment]
Looks like hypre was built w/ OpenMPI, but rsmpi is using mpich mpiexec. Is that correct?

**Comment by robnagler** [comment]
Hypre was built with mpich2. OpenMPI is not in our Jupyter image so Hypre couldn't have been compiled with it.

Hypre is installed by our software in `~/.local/lib/libHYPRE.a` and `~/.local/include`. Is this the version you are using?

**Comment by JohanCar1sson** [comment]
No, I was using /home/vagrant/jupyter/local/hypre-2.15.1/lib/libHYPRE.a

I'm using the mpich built hypre now. Still won't build Flash, but not due to OpenMPI/mpich incompatibility, so I'm closing this issue.

Thanks!

**Comment by JohanCar1sson** [comment]
OK, I'm reopening. I now get a different mpiexec error:

CapLaserBELLA-001$ rsmpi -n 8 flash4
[mpiexec@rs14.local] match_arg (utils/args/args.c:159): unrecognized argument mca
[mpiexec@rs14.local] HYDU_parse_array (utils/args/args.c:174): argument matching returned error
[mpiexec@rs14.local] parse_args (ui/mpich/utils.c:1596): error parsing input array
[mpiexec@rs14.local] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1648): unable to parse user arguments
[mpiexec@rs14.local] main (ui/mpich/mpiexec.c:149): error parsing parameters
CapLaserBELLA-001$ ldd flash4
        linux-vdso.so.1 (0x00007ffef52bc000)
        libhdf5.so.10 => /usr/lib64/mpich/lib/libhdf5.so.10 (0x00007f87b52cc000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f87b529e000)
        libmpifort.so.12 => /usr/lib64/mpich/lib/libmpifort.so.12 (0x00007f87b5262000)
        libmpi.so.12 => /usr/lib64/mpich/lib/libmpi.so.12 (0x00007f87b4fc5000)
        libgfortran.so.5 => /lib64/libgfortran.so.5 (0x00007f87b4d48000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f87b4bc4000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f87b4ba7000)
        libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007f87b4b64000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f87b499e000)
        libsz.so.2 => /lib64/libsz.so.2 (0x00007f87b4999000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f87b4993000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f87b4989000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f87b4965000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f87b55a6000)
        libaec.so.0 => /lib64/libaec.so.0 (0x00007f87b495a000)
CapLaserBELLA-001$

**Comment by robnagler** [comment]
Looking into this.

**Comment by robnagler** [comment]
@JohanCar1sson try it now

**Comment by JohanCar1sson** [comment]
Should I restart the server?

CapLaserBELLA-001$ rsmpi -n 8 flash4
[proxy:0:0@fnl24b.bivio.biz] HYDU_sock_connect (utils/sock/sock.c:146): unable to get host address for rs14.local (1)
[proxy:0:0@fnl24b.bivio.biz] main (pm/pmiserv/pmip.c:185): unable to connect to server rs14.local at port 33103 (check forfirewalls!)

**Comment by robnagler** [comment]
Looking into it...

**Comment by robnagler** [comment]
Try again. I executed in your container and works fine. Our alpha and beta systems are configured slightly differently, which is why I didn't detect his particular case.

**Comment by JohanCar1sson** [comment]
rsmpi works again! The only difference between new mpich rsmpi and the old OpenMPI one is that the current directory is no longer automatically added to the search path for executables. That is I had to prefix a dot slash for mpiexec to find the flash4 executable in the current directory:

rsmpi -h 2 -n 8 ./flash4

Life is good again, thanks!

**Comment by robnagler** [comment]
Great, sorry for the trouble. Good to know about the ./.
