### ISSUE TITLE
Problem with Flash 4.6.1 linked with mpich on jupyter

### ISSUE THREAD

**Issue by JohanCar1sson** [radiasoft/devops#185]
I had a Flash 4.6.1 simulation die from an MPI error halfway through on jupyter (error msg at bottom of this post). The exact same simulation runs fine on my home office Linux workstation. The crash on jupyter is reproducible: two different simulations, ran on different days, experienced the same error on the same time step.

Flash 4.6.1 was built with mpich 3.2.1 on both machines and simulation input is identical. The only difference is OS and gcc version:
gcc version 8.3.1 20190223 (Red Hat 8.3.1-2) (GCC)
vs.
gcc version 7.4.1 20190424 [gcc-7-branch revision 270538] (SUSE Linux)

Fatal error in PMPI_Comm_dup: Other MPI error, error stack:
PMPI_Comm_dup(177)..................: MPI_Comm_dup(comm=0xc40053e9, new_comm=0x7ffd44113b00) failed
PMPI_Comm_dup(162)..................: 
MPIR_Comm_dup_impl(57)..............: 
MPIR_Comm_copy(739).................: 
MPIR_Get_contextid_sparse_group(614): Too many communicators (0/2048 free on this process; ignore_id=0)

**Comment by robnagler** [comment]
I need to know how to run the example. I can get into your directory so if you can tell me which directory and the command line, I can figure it out.

I saw something about [MPIR_CVAR_CTXID_EAGER_SIZE](https://lists.mpich.org/pipermail/discuss/2013-July/003621.html) relate to FLASH so I'll try that first.

**Comment by JohanCar1sson** [comment]
I think it's safer to test in a fresh directory (I've noticed that overwritten data is a bit corrupted).
So:
$ cd /home/vagrant/jupyter/flash/FLASH4.6.1
$ ./setup -auto CapLaserBELLA -2d -nxb=28 -nyb=28 +hdf5typeio species=fill,wall +mtmmmt +usm3t +mgd mgd_meshgroups=6 -parfile=bella_setup.par -objdir=MpichTest +laser ed_maxPulses=1 ed_maxPulseSections=4 ed_maxBeams=1
$ cd MpichTest
$ make
$ mpiexec -n 4 ./flash4

It will run for a day or so before crashing...

**Comment by JohanCar1sson** [comment]
Correction: the two cases that crashed had resolution "-nxb=32 -nyb=32" and " -nxb=24 -nyb=24", respectively. So use the latter, it will run faster,

$ ./setup -auto CapLaserBELLA -2d -nxb=24 -nyb=24 +hdf5typeio species=fill,wall +mtmmmt +usm3t +mgd mgd_meshgroups=6 -parfile=bella_setup.par -objdir=MpichTest +laser ed_maxPulses=1 ed_maxPulseSections=4 ed_maxBeams=1

etc.

"-nxb=28 -nyb=28" would probably crash too, but I haven't verified that.

**Comment by JohanCar1sson** [comment]
I spun up a new server last Friday, and this issue persists. Should the mpich library be rebuilt with the value of MPIR_CVAR_CTXID_EAGER_SIZE increased?

**Comment by robnagler** [comment]
Getting build errors:

```txt
hy_uhd_getFaceFlux.F90:101:56:

                                             hy_uhd_HLLD,&
                                                        1
Error: Symbol ‘hy_uhd_addbiermannbatteryterms’ referenced at (1) not found in module ‘hy_uhd_interface’
```

I'll look into this, just documenting here.

**Comment by robnagler** [comment]
@ncook882 @JohanCar1sson I'm using CapLaserApril062019.tar.gz, which is referencing hy_uhd_addBiermannBatteryTerms in hy_uhd_getFaceFlux.F90, which seems to be a copy of source/physics/Hydro/HydroMain/unsplit/hy_uhd_getFaceFlux.F90 but with significant differences including this:

```diff
102c104,105
<                                             hy_uhd_addBiermannBatteryTerms
---
>                                             hy_uhd_addHallFluxes,&
>                                             hy_uhd_addBiermannFluxes
```

I suspect therefore that this file needs to get updated. 

@JohanCar1sson if you could give me the file(s) for CapLaserBELLA, I could maybe run the same test you are running.

**Comment by JohanCar1sson** [comment]
The issue with CapLaserApril062019.tar.gz was resolved on 09/19/19.

However, my instructions for how to reproduce the error reported in this issue (written down on 10/01/19, but still good, I just tested them) make no mention of that file.

For your convenience, I've made a tarball called "CapLaserBELLA.tgz". There's a copy in my jupyter home dir, as well as in my personal ownCloud folder. The tarball should be unpacked in FLASH4.6.1/source/Simulation/SimulationMain.

Then configure in FLASH4.6.1 with:
./setup -auto CapLaserBELLA -2d -nxb=24 -nyb=24 +hdf5typeio species=fill,wall +mtmmmt +usm3t +mgd mgd_meshgroups=6 -parfile=bella_setup.par -objdir=MpichTest +laser ed_maxPulses=1 ed_maxPulseSections=4 ed_maxBeams=1

and build with:
cd MpichTest
make

and run with:
mpiexec -n 4 ./flash4

**Comment by robnagler** [comment]
I was able to build and run the program in my VM and on Jupyter. It prints out a line for each `n`. All four cores are in use.

I built this with 4.6.2, because that's the version I had. I can try with 4.6.1, but I suggest that if this works, then it might be better to use 4.6.2.

@JohanCar1sson I uploaded a build script with everything in it in your Jupyter folder. You can:

```sh
cd ~/jupyter
tar xf flash-test.tar
cd flash-test
bash build.sh
```
