### ISSUE TITLE
Unchecked destroy/cancel to designhints

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#187]
@e-carlin wrote:
> Random thought - As we make the system more robust we'll need to add timeouts to messages. In the case of a timeout for a do_compute message we'll likely want to send a cancel after the timeout in case the job is running. But, we don't actually have any clue if the job is running so the cancel should succeed regardless. +1 for unchecked destroy.

**Comment by e-carlin** [comment]
Done https://github.com/radiasoft/pykern/wiki/DesignHints#unchecked-destroycancel

**Comment by robnagler** [comment]
Minor changes. Acronyms like D/C are rarely useful, better to have a word (I replaced with Destroy) that represents the class.
