### ISSUE TITLE
Notebook export to PDF not working

### ISSUE THREAD

**Issue by JohanCar1sson** [radiasoft/devops#188]
File -> "Export Notebook to PDF" fails with the error message below. A workaround is to export notebook to HTML, then manually convert HTML to PDF.

500 : Internal Server Error
The error was:

nbconvert failed: Pandoc wasn't found.
Please check that pandoc is installed:
http://pandoc.org/installing.html

**Comment by robnagler** [comment]
Notes to myself: 

Installed pandoc, but getting:

```txt
LaTeX Error: File `tcolorbox.sty' not found.
```

**Comment by dtabell** [comment]
The tcolorbox package is part of texlive.

**Comment by robnagler** [comment]
There's a list of *sty files that I need to chase down, one at a time. I started doing this, then ran into the issues This probably is the only approach that will work. I installed the full texlive, and it increased the size of my VM by 4G. I don't think that's reasonable to bring that in to be able to use this feature.

**Comment by dtabell** [comment]
Yes. The full texlive is huge. Putting it on the VM is a non-starter.
Some useful information is at
https://tex.stackexchange.com/questions/329986/
See also `tlmgr`.

**Comment by JohanCar1sson** [comment]
It might be possible to individually install the needed texlive packages with the Fedora package manager (zypper on openSUSE can do it). Even then it might take a few iterations to get things working. TeX must be sponsored by storage manufacturers!

**Comment by robnagler** [comment]
I'll debug it, but it is going to take time. I was doing a release of jupyter today so I thought I'd just install pandoc and it would work.

**Comment by robnagler** [comment]
I think this is fixed.
