### ISSUE TITLE
upgrade OPAL in containers

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#189]
Currently we have OPAL version 2.0.1 which is quite old. I checked with Chris and Stephen and we think going to version 2.1.0 would be better.

**Comment by robnagler** [comment]
@sdwebb @cchall The Wiki [says 2.0.1 is the current release](https://gitlab.psi.ch/OPAL/src/wikis/download-source).

[The tags](https://gitlab.psi.ch/OPAL/src/tags) show OPAL-2.2.0, OPAL-21.11.2019, OPAL-2.0.2. There doesn't seem to be a 2.1.0. Should I use 2.2.0?

**Comment by moellep** [comment]
What does the version show when building from the master branch: https://gitlab.psi.ch/OPAL/src?

**Comment by robnagler** [comment]
That says 2.1, but there's no corresponding tag so every time we build, we will get a different version. For example, there was a commit yesterday.

If that's what you want, then say "please build from master", not "version 2.1.0". 

I can also take a snapshot, which I update manually. Please specify this, if that's what you want.

**Comment by cchall** [comment]
I think building off of 2.2.0 is ideal for us.
There is at least one feature listed in the release notes: https://gitlab.psi.ch/OPAL/src/wikis/ReleaseNotes/OPAL-2.2 that might be needed for fastfelo.
