### ISSUE TITLE
graphviz in sirepo container

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#192]
Can we add graphviz to the sirepo container? It is used by the python module pydot which is used by rcscon.

**Comment by robnagler** [comment]
There seem to be a lot of options, e.g. freetype and Tcl. Are you using it now, if so how is it built?

**Comment by moellep** [comment]
I used the standard fedora one - "dnf install graphviz". It looks like it is used by the kera's function below. 

https://www.tensorflow.org/api_docs/python/tf/keras/utils/model_to_dot

And the call to that in sirepo is:

https://github.com/radiasoft/sirepo/blob/rcscon/sirepo/package_data/template/rcscon/graph.py.jinja#L9
