### ISSUE TITLE
Warp Import Error on Jupyter Server

### ISSUE THREAD

**Issue by cchall** [radiasoft/devops#20]
Trying to run Warp in an IPython notebook on the Jupyter server on the blade by running the standard Warp import command:
`from warp import *`

Results in the error:

> usage: __main__.py [-h] [-p DECOMP DECOMP DECOMP] [-l LOCALFLAGS]
                   [--pnumb PNUMB]
__main__.py: error: unrecognized arguments: -f /home/vagrant/.local/share/jupyter/runtime/kernel-5336e0f5-6a55-47c3-ba4f-1a37654a5290.json

Trying to import Warp through warp_init_tools gives a similar error.
Calling a Python Warp command file from the command line will run Warp successfully.

**Comment by robnagler** [comment]
Worked around with:

```python
import sys
del sys.argv[1:]
from warp import *
```

Fix will be tracked with radiasoft/containers#24
