### ISSUE TITLE
full stack sample sirepo server install fails

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#203]
Following the steps in the Full Stack Sample Server Configuration in the sirepo Development wiki, this step fails:

```
$ sudo su - -c 'radia_run redhat-docker'
Log: /root/radia-run-install.log
curl -L -s -S https://api.github.com/repos/radiasoft/download/contents/installers/redhat-docker/radiasoft-download.sh
Source: /var/tmp/radia-run-5732-30564/20200619163122-radiasoft-download.sh
  Can't initialize physical volume "/dev/sdb" of volume group "docker" without -ff
  /dev/sdb: physical volume not initialized.
```

**Comment by moellep** [comment]
Running "vgremove docker" as root and trying again seems to fix the problem. Maybe the "radia_run redhat-docker" is already performed by a prior step?

Continuing the steps, when you get to here:
```
# systemctl start sirepo_job_supervisor
Failed to start sirepo_job_supervisor.service: Unit not found.
```

The /srv/ directory shows only docker:
```
# ls /srv/
docker
```

**Comment by robnagler** [comment]
This was running in an unclean directory which had a persistent volume, but it was not setup properly. You would need to remove the device from virtualbox.

I added a check for this.
