### ISSUE TITLE
Building FEniCS in VM

### ISSUE THREAD

**Issue by dtabell** [radiasoft/devops#213]
For the SILAS project, we need to solve 3D PDE's.
I want to test [FEniCS](https://fenicsproject.org/).
One attraction of FEniCS is that it has a JupyterLab interface.
I can't use the docker image on the RS Jupyter server, so
am trying to build on my VM.

At the moment, this is not working for me, so help/ guidance
will be much appreciated.

**Comment by robnagler** [comment]
I started on this, but I had a lot of meetings today so probably finish tomorrow.

**Comment by robnagler** [comment]
Fix https://github.com/radiasoft/download/commit/a3e3de536cd136856c964a884d4d22f214c3b963 but need to build first, which is happening now.

**Comment by robnagler** [comment]
@dtabell run these two commands on your VM:

```sh
sudo dnf update -y
sudo dnf install -y rscode-fenics
```

The first one is necessary, because there were conflicts with packages that have to be resolved first. The second installs fenics, mshr, dolfin, petsc, and slepc. 

Please let me know if this works.

**Comment by robnagler** [comment]
fenics not working:

```txt
$ python -c 'import fenics'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/fenics/__init__.py", line 7, in <module>
    from dolfin import *
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/dolfin/__init__.py", line 142, in <module>
    from .fem.assembling import (assemble, assemble_system, assemble_multimesh,
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/dolfin/fem/assembling.py", line 34, in <module>
    from dolfin.fem.form import Form
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/dolfin/fem/form.py", line 12, in <module>
    from dolfin.jit.jit import dolfin_pc, ffc_jit
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/dolfin/jit/jit.py", line 18, in <module>
    raise RuntimeError("Could not find DOLFIN pkg-config file. Please make sure appropriate paths are set.")
RuntimeError: Could not find DOLFIN pkg-config file. Please make sure appropriate paths are set.
```

Fixes in https://github.com/biviosoftware/home-env/commit/1b6c61ca2bb91ea166237e6a4d0bd20c328add2a and https://github.com/radiasoft/download/commit/53cf8c1027c4718ac59853203b568559a501c834 and https://github.com/radiasoft/container-beamsim-jupyter/commit/be5c142d2388f4ec5400fedce0d26ba76f7b4dbb

Builds happening now.

**Comment by robnagler** [comment]
@dtabell are you up and running?

**Comment by robnagler** [comment]
Yup.
