### ISSUE TITLE
Building FEniCS in a VM

### ISSUE THREAD

**Issue by dtabell** [radiasoft/devops#214]
For the SILAS project, we need to solve 3D PDE's.
I want to test [FEniCS](https://fenicsproject.org/).
One attraction of FEniCS is that it has a JupyterLab interface.
I can't use the docker image on the RS Jupyter server, so
am trying to build on my VM.

At the moment, this is not working for me, so help/ guidance
will be much appreciated.

**Comment by robnagler** [comment]
Dupe of #213
