### ISSUE TITLE
3D viz for FEniCS in Jupyter notebooks.

### ISSUE THREAD

**Issue by dtabell** [radiasoft/devops#216]
As part of the silas project, I am working with the open-source PDE solver [FEniCS](https://fenicsproject.org/) in my VM and using Jupyter notebooks to organize, annotate, and render graphical displays of numerical results.

The FEniCS computations seem to be working. My example I checked into [rslaser](https://github.com/radiasoft/rslaser/tree/master/examples/notebooks/thermal_transport). One of the next tasks on my list is the 3D visualization. This is hampered (!) by the fact that FEniCS uses an _unstructured_ mesh, and all the matploblib functions that seem relevant (and that I've found) request a _structured_ mesh. The following figure illustrates the difference between structured and unstructured meshes:
<img width="996" alt="StructVUnstruct-mesh" src="https://user-images.githubusercontent.com/11483676/100939418-7912d600-34b3-11eb-9d1e-76e2fb7d0c89.png">
Evidently, an unstructured mesh requires significantly more data to describe all its nodes, edges, and (in 3D) faces.

For 3D viz, I have considered [ParaView](https://www.paraview.org/), which seems very capable, but a pain to install. (It’s “brought to you” by the same people who developed CMake.) Another option is [vedo](https://github.com/marcomusy/vedo), mentioned by people at the FEniCS project. It looks way(!) easier to install (`pip install vedo`) but I have not managed to get it to work for me in a Jupyter notebook. I [communicated with the developer](https://github.com/marcomusy/vedo/issues/248), but I'm still not there yet. I did push to the [repo](https://github.com/radiasoft/rslaser/tree/master/examples/notebooks/thermal_transport) one of the vedo demos that I’m using as a test.

**Comment by mkeilman** [comment]
I'm going to look at warpvnd, which uses unstructured meshes for some of its visualizations

**Comment by robnagler** [comment]
This is a priority.

**Comment by cchall** [comment]
If you're using triangular meshes I've had good success with plotly, which we already have installed, for 3D visualization in notebooks. 
![image](https://user-images.githubusercontent.com/17073688/100946836-761ee200-34c1-11eb-8753-bbaaf3117313.png)
