### ISSUE TITLE
rootless docker for nodes

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#221]
https://docs.docker.com/engine/security/rootless/

**Comment by e-carlin** [comment]
Exciting! FYI - need to use cgroupsv2 to be able to constrain resources in containers (ex --cpus) which we use in Sirepo. https://docs.docker.com/engine/security/rootless/#limiting-resources

**Comment by robnagler** [comment]
Argh:

```sh
# mount -t cgroup2 none /media
mount: unknown filesystem type 'cgroup2'
```
