### ISSUE TITLE
lz4-devel and nexusformat/HDF5-External-Filter-Plugins

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#226]
The CHX beamline data is compressed using a LZ4 hdf5 filter.

In addition to the mongodb, we'll need:

nexusformat/HDF5-External-Filter-Plugins built with -DENABLE_LZ4_PLUGIN=yes

which requires "dnf install lz4-devel"

(This is for jupyter users)

**Comment by robnagler** [comment]
I think we may not want this on by default. It might be picked up by all h5 utility users so new files might get compressed with lz4, and be incompatible with other apps.

**Comment by moellep** [comment]
Yes, I think we should keep it off by default. In a jupyter notebook, you can use the %env command to setup the plugin search as the first command, for example:

```python
%env HDF5_PLUGIN_PATH /home/vagrant/src/nexusformat/HDF5-External-Filter-Plugins/build/plugins/
import numpy as np
import matplotlib.pyplot as plt
from databroker import Broker
```

**Comment by robnagler** [comment]
I think we'll want a "setup bluesky" script (@e-carlin is working on this) that will also start mongodb. We can have it put the HDF5_PLUGIN_PATH in the users's environment `~/jupyter/bashrc`, which gets loaded before juptyerlab starts so it gets inherited. We will need to tell them to stop/start their server.

We don't want them putting that path in every notebook.
