### ISSUE TITLE
Installing Smilei on Sirepo

### ISSUE THREAD

**Issue by abdoudiaw** [radiasoft/devops#227]
I am trying to install [smilei](https://smileipic.github.io/Smilei/installation.html) (pic) code on sirepo. All the needed dependencies are already installed. But when linking the exec file with my python, I got this error:

```
Linking smilei
/usr/bin/ld: cannot find -lpython3.7m
collect2: error: ld returned 1 exit status
make: *** [makefile:249: smilei] Error 1
```

Any idea how to fix this?

The code lives here:
/home/vagrant/jupyter/StaffScratch/diaw/Smilei

**Comment by e-carlin** [comment]
@abdoudiaw if you use `LDFLAGS="-L /home/vagrant/.pyenv/versions/3.7.2/lib/" make` that should work. Reopen and lmk if not.
