### ISSUE TITLE
replace travis-ci.org with something

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#230]
It looks like the last three alpha releases have no comment. I manually added info from the pull requests to the most recently closed alpha release.

**Comment by robnagler** [comment]
travis-ci.org is now in readonly mode. Apparently they didn't transfer our stuff over. May be time to get buildbot or something else going on our side.

**Comment by robnagler** [comment]
@moellep you can run `bash sirepo-issue.sh` any time, and it'll bring in all commits in the last 24 hours. I'll have it running as a part of patrol.sh.

**Comment by robnagler** [comment]
Also deleted the webhooks for pykern and sirepo because they were printing red checkmarks on the commits incorrectly.

**Comment by robnagler** [comment]
GH Actions
