### ISSUE TITLE
RayData - library modifications required to run analysis notebooks

### ISSUE THREAD

**Issue by ncook882** [radiasoft/devops#231]
I've updated the raydata repo to include a cleaned up version of the [XPCS analysis notebook](https://github.com/radiasoft/raydata/blob/main/AnalysisNotebooks/XPCS_SAXS/XPCS_SAXS.ipynb) for the CHX beamline.

To run the notebook on beamsim, a number of libraries must be installed, and several patches applied.

1. pip install the following: 
- `databroker-pack`
- `pychx`
- `ModestImage`
- `xray-vision`
- `pyOlog`
- `area_detector_handlers`

2.  Manually install the [eiger-io](https://github.com/NSLS-II/eiger-io) library
3. Install the [HDF5 external plugin](https://github.com/nexusformat/HDF5-External-Filter-Plugins) library supporting lz4 compression. This is the subject of issue #226. @moellep provided me with a pre-compiled version and a patch cell in the notebook

```
import event_model
event_model.register_coercion('force_numpy', event_model.as_is, overwrite=True)
%env HDF5_PLUGIN_PATH /home/vagrant/src/nexusformat/HDF5-External-Filter-Plugins/build/plugins/
```

4.  Ammend the eiger-io library by modifying `fs_handlers.py` to replace `f[v].value` with `f[v][()]` - see the raydata repo [patch](https://github.com/radiasoft/raydata/blob/main/AnalysisNotebooks/XPCS_SAXS/patches/fs_handler.py)
5. Ammend import statements in pyCHX `chx_crosscor.py` to get rid of scipy version conflicts - link to [patch](https://github.com/radiasoft/raydata/blob/main/AnalysisNotebooks/XPCS_SAXS/patches/chx_crosscor.py)
6. Replace top level `__init__` file in xray-vision to fix sip import error - link to [patch](https://github.com/radiasoft/raydata/blob/main/AnalysisNotebooks/XPCS_SAXS/patches/__init__.py)

Once you've done this, you'll need two additional pieces of data:

1. The `chx-export` data, which Maksim has [shared](https://www.dropbox.com/s/6xxgfiszbo44zzw/chx-export-sanitized.tar.gz?dl=0) with us. After downloading and unpacking the tarball, you will need to run  the databroker unpack command on the cleaned up data, being sure to name the resulting catalogue `chx`, for example:
`databroker-unpack inplace /home/vagrant/jupyter/RayData/chx-export/ chx`

2. In order to run the portions of the notebook requiring masks, you will need access to the [mask files](https://www.dropbox.com/s/rp27xt3ijtxk8cj/XPCS_SAXS_2021_1_v2-for-radiasoft.tar.gz?dl=0) provided by Maksim. Some of these files are very large, so I omitted them from the repo. As noted in the notebook header, you'll need to unpack the mask files and point to their directory via the `mask_path` variable in order to run portions of the notebook.

**Comment by e-carlin** [comment]
Thanks for the details @ncook882. Couple questions:

1. Can you give me access to the raydata repo? I get a 404 currently.
2. What would you like me to do with this stuff? Would you like it all to be installed in beamsim so you don't have to manually do these steps?

**Comment by ncook882** [comment]
Thanks @e-carlin. 

1. I've added you to the repo with write access.
2. That's correct. It would be nice if the beamsim container could support the execution of these notebooks by default. You don't have to worry about pre-loading the data or mask files though.

**Comment by bnash** [comment]
Two minor bugs in notebook:
In cell below "Specify directories for masks and saving results"
- chx_export_parth -> chx_export_path
- username  is defined in cell below, after it is needed

**Comment by ncook882** [comment]
@bnash these have been fixed in https://github.com/radiasoft/raydata/commit/b3fdef2b0ac9dc190396c203bf868b4c430462a4

**Comment by e-carlin** [comment]
@robnagler I'm going to package this all up in an rpm. Also, since we don't have an immediate plan to use mongo and it seem lz4 pertains more to this than to mongo I'm going to move the lz4 install out of mongo and into this rpm. Sound good?

**Comment by robnagler** [comment]
You know more about this than I do. :)
