### ISSUE TITLE
RayData - RPMs for launching IPython with appropriate environment

### ISSUE THREAD

**Issue by ncook882** [radiasoft/devops#232]
This is a follow-up issue to #231. 

We need to be able to launch an IPython instance from a Sirepo application which will execute an XPCS analysis notebook such as the [example notebook](https://github.com/radiasoft/raydata/blob/main/AnalysisNotebooks/XPCS_SAXS/XPCS_SAXS.ipynb) in the raydata repo.

According to @robnagler, this requires updates to the RPMs included in beamsim, such that when the IPython instance is launched, the required dependencies can be efficiently included in the resulting IPython environment.

**Comment by robnagler** [comment]
@e-carlin please package the IPython install in an RPM including the config for the kernels, which might be necessary. You should be able to run nbviewer with the right version for JupyterLab (not packaging JupyterLab, which is distinct and more complicated). We can discuss when you are ready.
