### ISSUE TITLE
sirepo landing pages not moving from alpha to beta2

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#233]
It looks like the sirepo landing page changes weren't promoted during the last beta release, so they did not make it to prod today. What process promotes the landing pages?

**Comment by robnagler** [comment]
There are many steps the first time:

- WPEngine has to allow us to reverse proxy 
- Vermilion has to update the site url
- We update rsconf yaml

I'll take care of this tomorrow.

**Comment by robnagler** [comment]
done. we are still waiting to move to prod but that will be handled elsewhere.
