### ISSUE TITLE
gpu server cannot start new processes

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/devops#235]
This has happened a couple of times now on our gpu server. A user will try to start a new computation using the gpus and the processes will crash. Killing a user's docker container that is not currently in use seems to fix the problem. 

One hunch is that notebook kernels lock up gpu resources. Eventually this reaches a point where no new jobs can start.

Before killing the container `nvidia-smi` showed 2 processes running on each gpu. After killing the container it showed just one.

**Comment by robnagler** [comment]
Do we expect the GPUs to be shared? V100s don't have partitioning afaik. The `with` is probably not working right, and we probably need to lock/unlock the GPUs in our own contextlib

**Comment by e-carlin** [comment]
> Do we expect the GPUs to be shared?

Not sure. I suppose just using the slack channel to determine sharing fine. 

> The with

Is there specific code for this you can point me towards or are you talking in an abstract sense?

**Comment by robnagler** [comment]
I don't see how the GPUs could be shared, frankly, but maybe tensorflow is smart about that. 

I was talking about this code:

```py
  with tf.device('/device:GPU:2'):
```

Maybe this will help https://github.com/tensorflow/tensorflow/issues/1578

**Comment by jeinstei** [comment]
Just a comment, but pytorch seems to generally have better memory management, and Voltas can share jobs on a single GPU if the `nvidia-cuda-mps-control` daemon is running. I think that it works in dockers as they all see the GPUs the way we have things setup, but there are security concerns with that
