### ISSUE TITLE
In Jupyter notebook, all cell ids change on save.

### ISSUE THREAD

**Issue by dtabell** [radiasoft/devops#236]
This problem means that `git diff` on a `.ipynb` file can report many changes even in the absence of any “real” change in the notebook. Aside from the `diff` noise, it means the file hash changes and `git` tells me I need to commit the “updated” file.
[This issue](https://github.com/jupyterlab/jupyterlab/issues/9645), opened on 20 January in the [JupyterLab repo](https://github.com/jupyterlab/jupyterlab/), is (as of 15 May) now closed, which _implies_ this problem is now fixed. Is it possible to update JupyterLab, or whatever piece lower down that is responsible for this behavior? Or was the problem not truly fixed?

**Comment by robnagler** [comment]
It looks like this fix is part of JupyterLab 4.0, which [has yet to be released](https://github.com/jupyterlab/jupyterlab/projects/12).

The problem is the newest ipython version added cell ids, but jupyterlab wasn't updated to support them so they get regenerated each time. JupyterLab should 4.4, not 4.5. 

I don't think there's an easy fix for us.

**Comment by dtabell** [comment]
I'm confused: they’re working on 4.5, but have not released 4.0?

Anyways, I came across the following possibility:
https://github.com/jupyterlab/jupyterlab/issues/9729#issuecomment-806170280
Have not yet tried it.

**Comment by robnagler** [comment]
Notebook version 4.5. JupyterLab version 4.0.

This is part of our version hell. We will need to downgrade ipython to match this. It's not as easy as:

`python -m pip install --upgrade 'nbformat<5.1.2'`

**Comment by dtabell** [comment]
I guess that means for now we
```bash
sed -i -e '/"id": /d' *.ipynb
```
(or similar) before committing our notebooks in JupyterLab.

**Comment by robnagler** [comment]
done
