### ISSUE TITLE
latest version of Synergia is required for Jupyter on the blades

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/devops#24]
I need to run Synergia via Jupyter hub on the blades.
Recent fixes made by the Synergia development team are required.

The last commit that must be included:
commit 8d8761f3597a668b7d2ecc6bd770640006412af6
Author: Eric G. Stern <egstern@fnal.gov>
Date:   Fri Mar 25 17:17:11 2016 -0500

**Comment by robnagler** [comment]
We run a special branch of Chef. Do you know if the latest is required? I
had to fix a few things to get it to compile.

**Comment by bruhwile** [comment]
I strongly suspect that Chef has been changed.

Here's the input from the Synergia team:
#---
A summary of the relevant patches are below:

commit 8d8761f3597a668b7d2ecc6bd770640006412af6
Author: Eric G. Stern <egstern@fnal.gov>
Date:   Fri Mar 25 17:17:11 2016 -0500

    calculate bassetti-erskine space charge in lab frame results in less
spurious longitudinal motion

commit 7a05313e5954ddf617e7710ff1d2e260f2726ea1
Author: Eric G. Stern <egstern@fnal.gov>
Date:   Fri Mar 4 17:15:19 2016 -0600

    wrap new Space_charge_2d_bassetti_erskine method set_longitudinal and
the constants longitudinal_uniform, longitudinal_gaussian

commit e6154698c89fdf12d6436f6dc407a4daf3c85a03
Author: Eric G. Stern <egstern@fnal.gov>
Date:   Fri Mar 4 14:18:07 2016 -0600

    round and almost round sc calculation should return almost the same
field, also numerically check bassetti-erskine calculation at a few points
against a previous program.

commit 9c6b0ed97a3e39dc7523e185fb5a8bf180d28874
Author: Eric G. Stern <egstern@fnal.gov>
Date:   Fri Mar 4 14:16:53 2016 -0600

    have set_sigma return whether the beam is round

commit a1825714ad755c4a6526fc1099384bf48dbedea8
Author: Eric G. Stern <egstern@fnal.gov>
Date:   Thu Mar 3 11:01:41 2016 -0600

    new tests are all working, including with offset, checks on yp, linear
and gaussian line density
#---

Maybe we should issue a pull request to get the compilation problem fixed?

David

**Comment by robnagler** [comment]
I'll figure it out.

**Comment by robnagler** [comment]
Here are the options.

In your vagrant box:

```bash
```

**Comment by bruhwile** [comment]
I don't see the options...

**Comment by robnagler** [comment]
Sorry, {}-return accidentally pressed. I'm writing it now :)

**Comment by robnagler** [comment]
The prototype server has been upgraded. Let me know if the synergia works.

**Comment by robnagler** [comment]
@bruhwile I'm waiting to close this.

**Comment by bruhwile** [comment]
I confirmed that modifications to the 2D Basetti-Erskine solver are working correctly.
