### ISSUE TITLE
virtualbox.org is not responding

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#240]
Somebody forgot to put a redirect to:

https://www.oracle.com/virtualization/technologies/vm/downloads/virtualbox-downloads.html

We should update our documentation. Maybe want a redirect of our own, because I suspect (given this change) that they won't respect history so we don't have to update everywhere.

**Comment by e-carlin** [comment]
FWIW I can get it to load but it is intermittent.

**Comment by robnagler** [comment]
I imagine Oracle put it on the free tier at AWS. ;-)
