### ISSUE TITLE
20221015 /etc/vbox/networks.conf update required with virtualbox 6.1.30

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#241]
> The IP address configured for the host-only network is not within the
> allowed ranges. Please update the address used to be within the allowed
> ranges and run the command again.
>   Address: 10.10.10.10
>   Ranges: 192.168.56.0/21
> Valid ranges can be modified in the /etc/vbox/networks.conf file. For
> more information including valid format see:
>   https://www.virtualbox.org/manual/ch06.html#network_hostonly

**Comment by robnagler** [comment]
This works:

```sh
sudo su -
install -d -m 755 /etc/vbox
echo '* 0.0.0.0/0 ::/0' > /etc/vbox/networks.conf
chmod 644 /etc/vbox/networks.conf
```

There are various discussions about `v.gui`, but I think this is a red herring. I tried that, and it didn't change anything.

**Comment by robnagler** [comment]
Still needs to be automated.

**Comment by robnagler** [comment]
Fix https://github.com/radiasoft/download/issues/337

**Comment by e-carlin** [comment]
@robnagler I have the fix but I'm still unable to connect to a server running in fedora36. Are you able to connect?

**Comment by robnagler** [comment]
You mean this bug? https://github.com/radiasoft/download/issues/351

**Comment by robnagler** [comment]
Maybe this ? https://github.com/radiasoft/download/issues/328
