### ISSUE TITLE
how to configure line wrapping in jupyter

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#246]
@jeinstei writes:
> Does anyone know which config file to place the jupyter line-wrapping in? I've seen ~/.jupyter/nbconfig/notebook.json and ~/.ipython/profile_nbserver/ipython_notebook_config.py, depending, but I can't seem to get the line wrapping to kick in using the code here: https://stackoverflow.com/questions/43183173/how-do-you-wrap-lines-in-a-jupyter-notebook#43279885

**Comment by jeinstei** [comment]
Thanks for making the ticket

**Comment by gurhar1133** [comment]
Hi Josh,

If you open settings > advanced editor settings and click the notebook tab you'll see something like this
![Screen Shot 2022-03-11 at 3 50 16 PM](https://user-images.githubusercontent.com/49498231/157984964-be2db97a-7bbc-4810-8934-1d9fd5586aed.png)

In the user preferences editor if you add the snippet:
```json
{
    "codeCellConfig": {
        "lineWrap": "on"
    }
}
```
Like so:
![Screen Shot 2022-03-11 at 3 48 41 PM](https://user-images.githubusercontent.com/49498231/157984868-8a54a3ee-1ab2-4f92-9542-198a22212375.png)

you should get line wrapping
