### ISSUE TITLE
github_bkp.service loaded failed failed github_bkp

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/devops#249]
Logs on machine where backup ran say `ERROR: Command errored out with exit status 128: git clone -q git://github.com/radiasoft/pykern /tmp/pip-install-9ljzmuj5/pykern_69e3669e19974699bf767fc91b4\
c8e87 Check the logs for full command output`

First line of github_bkp is `pip --quiet --disable-pip-version-check install 'git+git://github.com/radiasoft/pykern#egg=pykern'` this failed for me when I tried to run it on my mac

**Comment by e-carlin** [comment]
I ran `systemctl reset-failed` on the affected host. I think with the fix to rsconf and this github_bkp should start working again.

**Comment by robnagler** [comment]
To run rsconf on the affected machine
