### ISSUE TITLE
use "distribution server" for mpi workers

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/devops#250]
Have a single server that is in control of .rsmpi file so workers nodes don't all require a reboot on change.

I don't exactly understand the problem but that is as best as I can describe it right now. I'll update the issue as I more fully understand the problem. First step in solving is getting a dev rsconf rsmpi configuration up and running.

**Comment by robnagler** [comment]
See https://github.com/radiasoft/rsconf/issues/172. Probably just close this one?

**Comment by e-carlin** [comment]
dup
