### ISSUE TITLE
Automate test suite runs on PRs

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#252]
We pay for github actions so let's use them:

- https://docs.github.com/en/actions/learn-github-actions
- https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration
- https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
- https://github.com/actions/starter-workflows/blob/main/ci/python-app.yml

Considerations:
- Look at how we do travis. 
- Add to projex 
- Add a "db upgrade" to projex so add something like `update-rs-tree` for this case
- Drop tox

Later:
- Push to pypi. tox/twine is broken so let's do something else. I think we should push pykern, rsbeams, etc. once a release goes to prod. Only packages with complete dependencies should be pushed. (Much later: Consider defining sirepo that gets pushed to support myapp only.)

**Comment by rorour** [comment]
@robnagler just opened a pr. Doesn't seem like it linked correctly... https://github.com/radiasoft/pykern/pull/181

**Comment by robnagler** [comment]
I know we can get github actions to work, but it is work, e.g. 

> /github/workspace - Note: GitHub Actions must be run by the default Docker user (root). Ensure your Dockerfile does not set the USER instruction, otherwise you will not be able to access GITHUB_WORKSPACE.
