### ISSUE TITLE
setup gpu server for ndviz

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/devops#255]
We need a server with a gpu for the ndviz project. At the start the gpu doesn't need to be very powerful. Just enough to run the system and view simple data. Can we use our internal gpu server or create one (ex on AWS)? @robnagler please advise.

**Comment by e-carlin** [comment]
I think our internal server will work in terms of CUDA versions.

**Comment by robnagler** [comment]
This is up to you. I think you should be the only one to use it for development. If you want to deploy something, we should just get a server in the cloud. This time I might want to try Azure or Linode.

**Comment by e-carlin** [comment]
Ok, I will use our internal server for the time being.
