### ISSUE TITLE
DC migration: enet switches and shelf

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#259]
The fast boxes (fnl225-227) connect over the external 10gbe on the MXL so we only need a 1gbe switch for the backnet. I think we might have another port or two so we can connect the new jump host there. The jump host only needs to be on the management net, which is currently a 1gbe which is sufficient. We can just migrate the physical 1gbe.

The new inet will be a 1gbe drop. We could get higher speeds, but we would get lower burst rates:

> Burstable multi-carrier IP Bandwidth including auto-DDoS mitigation. No burst limits when delivered on a port speed of 1Gb or less. On a 10Gb port, bursting is capped at 2 times the commit rate. Overage is billed at the 95th percentile on the higher of in or out traffic.

We are committing to 100mbps, which is 10x higher than we have today, so it should be enough. The 1gbe is therefore better. Also, the 10gbe is optical, and that would increase the switch cost.

Therefore, I think we can just buy what we [bought before](https://smile.amazon.com/gp/product/B00MPVR50A) or something "better". I have never had a netgear fail. Throughput never seems to be the problem of our connection, but I'd like your input.

We also need a shelf. We [bought this before](https://smile.amazon.com/gp/product/B0713SCDTC), but I think a deeper one would be better. I'd like to put the switches up front and the jump host in back. We are almost at the rack capacity so it needs to be 1U. We are going to have 5U (hopefully just 5U) taken up the PDUs. Before they were vertical, but that is problematic with the extra long boxes (gpu server).

**Comment by robnagler** [comment]
Since we have more room, I think we should put in two shelves, and not have a long shelf. The top shelf could be the top-of-rack switch and the jump host. The next shelf could be the management network. We can move the management network shelf from FNL. No need to buy another, since they are easy to install.

**Comment by e-carlin** [comment]
Another shelf and another gs108 switch was purchased.
