### ISSUE TITLE
DC migration: foam, sheets, and straps

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#261]
We need heavy foam maybe [like this](https://smile.amazon.com/dp/B01H2QS4N4) for the move. The foam should be a bit bigger than the big units, which we are going to try to move with blades in place. Plan B will moving with the blades separately. The foam should fit on the lift dolly. The foam probably doesn't have to be antistatic, because it will be touching the chassis only. We can kit it out with aluminum foil on the top which should help with the sliding.

Underneath the foam there should be a sheet of plastic sheet to be able to slide it into the truck(s). Due to the foam it will be "tipsy" so we have to be careful with this. Again, the plastic sheets can be [ordinary 6mil](https://smile.amazon.com/dp/B0040ZC5AO) unless you can find some antistatic. Think about alternative sliding solutions (straps?).

We will want to make sure everything is strapped down.  A plan is needed.

**Comment by e-carlin** [comment]
Each M1000 weighs about 300lbs. Do you think just wrangling by hand with dollies will work? What if I built a little pallet like the image below and we ran straps around so we could more easily lift them and tie them down in the back of cars?


![IMG-2601](https://user-images.githubusercontent.com/10264515/163473192-d868be88-409f-46ba-ad13-980e1c1d66b2.jpg)

**Comment by e-carlin** [comment]
I've been thinking about this more. Last time we installed one of these we couldn't lift it from the (broken) pallet onto the dolly without pulling all of the blades. How many people are going to be doing the move? If it is 4 people that are comfortable lifiting that much then I think it will be ok. Otherwise we should plan on removing the blades, taking the chassis and blades separate out to the cars, installing the blades in the chassis in the cars, drive down and reverse.

**Comment by robnagler** [comment]
We have [hydraulic lift tables](https://www.jegs.com/i/JEGS/555/81454/10002/-1) so we just need to be able to slide it on top of something and then slide it onto the bed of our cars. Plan B is to remove the m620s from the chassis. If the cars have tie downs, which I believe they do, then we should be fine with just resting on foam, not a pallet. Indeed, it might be that we can slide the m1000s on to the foam and slip it along with plastic underneath the foam.

**Comment by e-carlin** [comment]
@robnagler [here is the plan](https://docs.google.com/document/d/1Tve6Fy62w83w5USWNUbcrw-HCDo4GtMj8uVUom_2sR4/edit). You can leave comments there and I will address

**Comment by robnagler** [comment]
I modified the plan. I wrote up [the cable inventory at FNL this weekend](https://docs.google.com/document/d/1tOOOLi2S9sDpb_WuGN_J5M5dZrBLU-8A_8R3aM5D-iQ/edit?usp=sharing).
