### ISSUE TITLE
Enable command-line help for git on Jupyter

### ISSUE THREAD

**Issue by dtabell** [radiasoft/devops#277]
Would be real nice if `git help stash` or `git stash --help` were to yield something useful on Jupyter. In my case I see the message
```
warning: failed to exec 'man': No such file or directory
fatal: no man viewer handled the request
```
And `which man` reports
```
bash: type: man: not found
```

**Comment by e-carlin** [comment]
Dup ~~https://github.com/radiasoft/devops/issues/277~~ https://github.com/radiasoft/container-beamsim-jupyter/issues/59
