### ISSUE TITLE
rsopt doesn't work on devbox or devbox36

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#280]
This command runs OK on a mac vm, but fails on old and new devboxes:
```
$ rsopt sample configuration exportRsOpt.yml
usage: rsopt sample [-h] {} ...
rsopt sample: error: invalid choice: 'configuration' (choose from )
```

If I run with an invalid command on the mac vm, I get a list of choices, which seem to be missing on devbox.
```
$ rsopt sample bogus exportRsOpt.yml
usage: rsopt sample [-h] {configuration,restart,start} ...
rsopt sample: error: invalid choice: 'bogus' (choose from 'configuration', 'restart', 'start')
```

**Comment by cchall** [comment]
This is probably https://github.com/radiasoft/rsopt/issues/144, which should be fixed in the most recent version.
