### ISSUE TITLE
Confusion with OMP_NUM_THREADS when using rsmpi on Jupyter

### ISSUE THREAD

**Issue by ncook882** [radiasoft/devops#284]
Running with rsmpi on jupyter seems to ignore any specificatino of `OMP_NUM_THREADS`, and defaults to one thread per hyperthreaded core (e.g. 40 on our nodes). This seems to conflict with the designation in the [wiki](https://github.com/radiasoft/devops/wiki/rsmpi) and my understanding of how rsmpi  is leveraging mpiexec.

For example, running `rsmpi -h 1 -n 1 ./warpx.3d.MPI.OMP.DP.PDP.OPMD.QED dwfa_slab_hr` indicates

> MPI initialized with 1 MPI processes
> MPI initialized with thread support level 3
> OMP initialized with 40 OMP threads

while running `OMP_NUM_THREADS=20 rsmpi -h 1 -n 1 ./warpx.3d.MPI.OMP.DP.PDP.OPMD.QED dwfa_slab_hr` also indicates

> MPI initialized with 1 MPI processes
> MPI initialized with thread support level 3
> OMP initialized with 40 OMP threads

Increasing the number of mpi ranks results in an request for OMP threads in excess of the physical cores available and a warning from the WarpX code, as well as substantially decreased performance. For example. running `OMP_NUM_THREADS=1 rsmpi -h 1 -n 16 ./warpx.3d.MPI.OMP.DP.PDP.OPMD.QED dwfa_slab_hr` indicates 

> MPI initialized with 16 MPI processes
> MPI initialized with thread support level 3
> OMP initialized with 40 OMP threads
> AMReX Warning: You might be oversubscribing CPU cores with OMP threads.
>                There are 40 cores per node.
>                There are 16 MPI ranks per node.
>                But OMP is initialized with 40 threads per rank.
>                You should consider setting OMP_NUM_THREADS=2 or less in the environment.

Querying the environment variable `OMP_NUM_THREADS` via rsmpi returns `none`, which indicates that it should produce the default performance, which is one thread per rank.

Performing these manipulations, either through command line argument at runtime via mpiexec or environment variable change to `OMP_NUM_THREADS` produces the desired manipulation of the number of OMP threads. For example, `OMP_NUM_THREADS=4 mpiexec -n 4 ./warpx.3d.MPI.OMP.DP.PDP.OPMD.QED dwfa_slab_hr` returns the expected performance:

> MPI initialized with 4 MPI processes
> MPI initialized with thread support level 3
> OMP initialized with 4 OMP threads

I should also note that I've played around with setting this behavior using the `amrex` API  in Warpx (via `amrex.omp_threads`) and that has no effect on the behavior. The [documentation](https://warpx.readthedocs.io/en/latest/usage/parameters.html) suggests that this setting is secondary to any environment variables.

**Comment by k-wolfinger** [comment]
I am also seeing issues with this. I set `os.environ["OMP_NUM_THREADS"] =...` at the start of my picmi warpx script. When running on rsmpi, I changed this from `4` to `2` as recommended by the warning (like what Nathan showed above). The sim results showed beam injection 16x faster than when run on the local jupyter server.

**Comment by ncook882** [comment]
Thanks for the input @k-wolfinger . The script I'm working with is designed to use the pre-compiled WarpX binary, and I don't have a PICMI equivalent right now, so I was hoping for a non-Pythonic solution here. If it's essential, I can look into reproducing the script via the PICMI API.

**Comment by robnagler** [comment]
rsmpi doesn't muck with this so there's something going on. I'll debug.

**Comment by robnagler** [comment]
rsmpi unintentionally mucked with OMP_ vars by not passing them on. Fix deployed with https://github.com/radiasoft/rsconf/pull/470.

**Comment by sjcrs** [comment]
I had been running Geant4 with rsopt with the python command 

>  os.system("source /home/vagrant/jupyter/Radiabeam/geant4_11make.sh;export G4FORCENUMBEROFTHREADS=20;./TestEm7 "+full_filename+" > dump.txt")

to use 20 cores on MPI nodes, but I think the change described here was responsible for my jobs today pushing nodes up to load averages >200.  It took a while to figure out, and Chris was a big help.  It seems to run as I expect if I require `G4FORCENUMBEROFTHREADS=1`. I'm not requesting a change to the deployed fix, just pointing out that there might be effects felt by other codes
