### ISSUE TITLE
Cannot open files through the browser on jupyter.radiasoft.org

### ISSUE THREAD

**Issue by cchall** [radiasoft/devops#33]
Files ending in .py and .txt can no longer be opened through the file browser on JupyterHub. The files can still be selected and renamed, if the extension is changed the file can be opened as normal.

**Comment by robnagler** [comment]
I'm having versioning issues in github. Our patches (like for this one) need to be in, but their latest changes need to be out. Builds take a while so probably won't be done before 4 or 5.

**Comment by robnagler** [comment]
This is fixed but you have to let me know when I can restart your container. Unfortunately, you can't do this yourself.
