### ISSUE TITLE
Synergia needs to be updated on the Jupyter server

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/devops#36]
Two essential updates have been added to Synergia:
1) explicitly linear space charge forces (some weeks ago)
2) corrected implementation of nonlinear 'elliptic' magnet for the IOTA ring (yesterday)

We need these on the Jupyter server for the IOPTICS project.

The 'chef' library has definitely been updated.
Here's a comment from the development team:

The NonLinearPropagators.cc file lives in the build/chef-libs hierarchy.  If you do a brand new build of everything you will get the updated code.  Alternatively, if you do a

    git pull
    make install

inside of the chef-libs directory, you will be updated with the fix.

**Comment by robnagler** [comment]
Images installed on all nodes in Jupyter cluster. I removed the running containers, because they seemed idle.
