### ISSUE TITLE
git tutorial

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#42]
Prepare and give tutorial on git topics for the team. This includes expanding the [Git wiki](../wiki/Git).
- GitHub comments/subjects (maybe
- reflog, what's that?
- rebase/merge? 
- resets (commits, unstaged, etc.)
- stash
- what's the RadiaSoft workflow look like

**Comment by robnagler** [comment]
@elventear can we close this, i.e. did you put what you wrote in a wiki?

**Comment by elventear** [comment]
I wrote the Wiki entries, I think it was good start. Did not cover the workflow area.
