### ISSUE TITLE
file download option on Jupyter server is broken

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/devops#44]
If you select the square to the left of a filename in the Jupyter server, a new UI pops up with options:
  Duplicate Rename Move Download <trash logo>

See screenshot:
![image](https://cloud.githubusercontent.com/assets/3825435/18493254/c3f276a4-79cc-11e6-82c2-181ca4f534bb.png)

Selecting the 'Download' button should download the file, but instead you see the error message here:
![image](https://cloud.githubusercontent.com/assets/3825435/18493279/ecbaf098-79cc-11e6-8b04-bde01e1b1ab5.png)

**Comment by bruhwile** [comment]
This has been reported by another user.

The work around is to right click (or the Mac equivalent) on the name of the file you want to download, and then select 'Save link as...' (or the Mac equivalent).

**Comment by bruhwile** [comment]
My suggested work around doesn't actually work. A user tells me:
"The workaround I’ve found is to go into the file and then do “File->Download”, but of course this will only work for text files."

This needs to become a high priority issue as of December 14.

**Comment by robnagler** [comment]
this button is gone so closing.
