### ISSUE TITLE
Jupyter containers need to support matplotlib-compatible video encoders

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/devops#47]
For example FFMPEG  https://ffmpeg.org/ 
and/or other matplotlib-compatible encoders

This capability is already required for the Jupyter notebooks we are delivering to a customer.

**Comment by robnagler** [comment]
@elventear Would you figure out how to install ffmpeg? I think it would probably make sense to have available in general, since we use the beamsim container in other contexts.

**Comment by elventear** [comment]
What is the priority of this?

**Comment by bruhwile** [comment]
It's a feature request.

I don't know how to rank compared to your other activities.

David

**Comment by robnagler** [comment]
SOS2016 takes priority. That has to be stable mid-week. After that we can
do this.

**Comment by elventear** [comment]
The [RPM Fusion](http://rpmfusion.org/Configuration) repo, has ffmpeg available for Fedora 21. This is the suggested source for RHEL and Fedora by the ffmpeg project.

**Comment by robnagler** [comment]
Sounds good. When you add the repo make sure it is not enabled by default
so we don't accidentally pull other packages from RPM Fusion.
Alternatively, we can grab a specific version and copy it to
depot.radiasoft.

**Comment by robnagler** [comment]
@elventear Looks good. Did you merge?

**Comment by elventear** [comment]
Yes.
