### ISSUE TITLE
add rsbeams to PyPI

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/devops#49]
https://github.com/radiasoft/rsbeams

We have users of the Jupyter server, who need this library for use of our IPython notebooks.
We need them to be able to do 'pip install' and 'pip install --upgrade'

**Comment by robnagler** [comment]
See discussion in #50.

**Comment by bruhwile** [comment]
Having pip install work via git+git is fine for now.
I suggest labeling this issue as low priority and putting it off for a while.

**Comment by robnagler** [comment]
pip is sufficient, and we'll build beamsim automatically soon enough.
