### ISSUE TITLE
Add matplotlib .mplstyle files to container for Jupyter server

### ISSUE THREAD

**Issue by ncook882** [radiasoft/devops#51]
We currently have a set of .mplstyle files for making plots with a standardized appearance.

https://github.com/radiasoft/rsbeams/tree/master/rsbeams/matplotlib

At this point, users need to clone rsbeams and copy the files to their own folder. Instead, it would be nice if the container automatically copied the `stylelib` folder and its contents into the `/home/vagrant/.config/matplotlib/` folder, so that users have this feature automatically.

**Comment by robnagler** [comment]
@ncook882 Do you want rsbeams to be installed automatically with the container? 

Is the copy command exactly this?

```sh
cp -a ~/src/radiasoft/rsbeams/rsbeams/matplotlib/stylelib ~/.config/matplotlib
```

Not clear from the text if the copy is stylelib or stylelib/*.

**Comment by ncook882** [comment]
`stylelib/*` should be correct. You want to copy all of the .mplstyle files into the matplotlib config folder.

**Comment by robnagler** [comment]
Added in [2fc9f9084fdf0b9c767f19a5cd1bb82b2c8ee7d8](https://github.com/radiasoft/jupyter.radiasoft.org/blob/2fc9f9084fdf0b9c767f19a5cd1bb82b2c8ee7d8/radia-run.sh#L33) to [radiasoft/jupyter.radiasoft.org](https://github.com/radiasoft/jupyter.radiasoft.org), which allows dynamic container customization through a curl installer. [Please read the README](https://github.com/radiasoft/jupyter.radiasoft.org/blob/master/README.md) to learn how to add global and personal customizations. 

The latest juypterhub will now stop the container when you say "stop server" so this allows users to control when they upgrade their containers to the latest code. 

I'm in final stages of testing and will push shortly (hopefully :).
