### ISSUE TITLE
add rslinac and dependencies to beamsim container

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/devops#56]
We need rslinac running on our Jupyter server and it also needs to be available to Sirepo

bill time to HIPOLIN project

**Comment by robnagler** [comment]
@bruhwile how would rslinac be used in Sirepo now? Would it be sufficient to add it to the Jupyter container (for now)?

**Comment by robnagler** [comment]
@elventear I'm getting a failure when I try to pip install rslinac. Here's the first one:

```text
src/physics/Types.h: At global scope:
src/physics/Types.h:421:20: error: ‘ifstream’ was not declared in this scope
```

I'm assuming this is due to an update in the code. Perhaps we need to mark a commit as being beta(?).

**Comment by bruhwile** [comment]
Early in 2017, I'll ask @moellep to implement a prototype Sirepo UI for rslinac.
So this task is not urgent.
Yes, for now it's sufficient to simply install it in the container, or even just to have pip install working.

**Comment by elventear** [comment]
`rslinac_rename` is the stable branch.

**Comment by robnagler** [comment]
Should make sure that we do an pip install --upgrade --nodeps so that we pull in the latest without upgrading dependencies. The full incantation is:

```
pip install --upgrade --no-deps <pkg>
pip install <pkg>
```

The second line ensures non-existent dependencies are installed.

**Comment by elventear** [comment]
@bruhwile `rslinac` is available with the latest code on the `beamsim` container. But when I did the porting originally, I never really tested the functionality of the code. Before someone tries to actually use it, I would like get some sample inputs that I could use to test from Python.

**Comment by bruhwile** [comment]
Thanks @elventear 

@moellep is able to run Hellweg on Windows with the Embarcadero GUI and he is tasked with creating a prototype Sirepo interfaced to the containerized version of `rslinac` .  

During the course of his work, @moellep will compare your compiled/containerized code with the original Windows-only build.

**Comment by elventear** [comment]
What I was trying to say is that the logic that sets up a simulation is not abstracted from the GUI code. So I had to replicate or adapt similar code to run a simulation for Python; although I did my best, I have no way to know if it works or if there is something missing.

**Comment by bruhwile** [comment]
Understood.

Please make @moellep aware of your Python-based API as he will need that
for his work.

If @moellep discovers bugs, then please assist him if necessary in working
them out.

Thanks!
