### ISSUE TITLE
comsol.radiasoft.org 404 error

### ISSUE THREAD

**Issue by moellep** [radiasoft/devops#57]
comsol.radiasoft.org was returning 404 errors for all pages. Restarting nginx on apa11 corrected the problem. I didn't see anything related errors in the nginx error logs. It looks like the problem also occurred on Oct 7.

comsol.radiasoft.org 68.168.180.89 - - [26/Oct/2016:01:22:08 -0600] "GET / HTTP/1.1" 404 0 "-" "-" "-"

**Comment by robnagler** [comment]
Had not found again. This time restart of nginx didn't do anything (or enough?). On apa11:

```sh
$ curl -D - http://apa19b.bivio.biz:2036
HTTP/1.1 404 Not Found
Content-Length: 0
Date: Mon, 07 Nov 2016 23:03:24 GMT
Server: Apache
```

So restarted comsol on apa19 and that seems to have fixed it.

**Comment by elventear** [comment]
Happened again today. @moellep restarted nginx and it did not help. Restarted Comsol afterwards and things were working again.

**Comment by robnagler** [comment]
What happens when you curl to the server on apa19?

**Comment by robnagler** [comment]
Hasn't been happening lately.
