### ISSUE TITLE
large ipython notebook saves fail

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#6]
@cchall writes:
So I discovered today while using an ipython notebook on the blade that the notebook will fail to save if it becomes too large. I'm not sure exactly what the size limit is or where the failure point occurs, but I was in the middle of  analyzing 1000, 1MB files when I discovered the failure.

While I can restart the kernel and clear all output and then make a save this is a little unsatisfactory as it would be preferable to be able to just save the notebook cells without having the notebook try to save output so that I don't have to stop work just to make a save. 

I'm not sure if this is a restriction that is being imposed by ipython or by the fact that I am running on the blade but I wanted to throw the problem out there.

**Comment by robnagler** [comment]
I bumped the front end's limit to 100mb. It was at default (1mb). @cchall please try again, and reply with status. Thanks.

There may still be a problem. See jupyter/notebook#650 for a discussion of limits in Tornado. 
I'm not sure what Jupyter defaults to, but it might be 100mb.

**Comment by cchall** [comment]
My current notebook now appears to be saving properly, though it is <100 MB. I'll try to set up a test with larger notebooks and see what happens.

I can also now upload files with size > 1 MB. However, I get a message:

"""
Cannot upload file

Cannot upload file (>25 MB) '99mb.txt'
""""

When I try a file >25 MB.

**Comment by robnagler** [comment]
This is a hard limit in Jupyter 4.x. See 
[this discussion](https://github.com/jupyter/notebook/pull/623#issuecomment-149890586) for the
[current workaround](https://github.com/jupyter/jupyter-js-filebrowser/search?utf8=%E2%9C%93&q=%22_max_upload_size_mb%22).
They are [waiting till 5.0](https://github.com/jupyter/notebook/issues/96#issuecomment-149585809)
to fix it.
