### ISSUE TITLE
jupyter synergia pre3 not loading correct library

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#61]
```
jupyter$ pyenv activate synergia-pre3
jupyter$ python
>>> import synergia       
```

**Comment by robnagler** [comment]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/synergia-pre3/lib/synergia/__init__.py", line 8, in <module>
    import foundation
  File "/home/vagrant/.pyenv/versions/synergia-pre3/lib/synergia/foundation/__init__.py", line 1, in <module>
    from foundation import *
ImportError: /home/vagrant/.pyenv/versions/synergia-pre3/lib/synergia/foundation/foundation.so: undefined symbol: _ZNK18Reference_particle8get_massEv
```

**Comment by robnagler** [comment]
There's an odd loading problem that didn't show up until I built the last container:

```text
fstat(17, {st_mode=S_IFREG|0755, st_size=426375, ...}) = 0
open("/home/vagrant/.pyenv/versions/synergia-pre3/lib/synergia/foundation/foundation.so", O_RDONLY|O_CLOEXEC) = 18
read(18, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p\270\2\0\0\0\0\0"..., 832) = 832
fstat(18, {st_mode=S_IFREG|0755, st_size=426375, ...}) = 0
mmap(NULL, 2391552, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 18, 0) = 0x7f7c0e6be000
mprotect(0x7f7c0e701000, 2093056, PROT_NONE) = 0
mmap(0x7f7c0e900000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 18, 0x42000) = 0x7f7c0e900000
close(18)                               = 0
open("/home/vagrant/.pyenv/versions/2.7.10/lib/libsynergia_foundation.so", O_RDONLY|O_CLOEXEC) = 18
read(18, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \244\3\0\0\0\0\0"..., 832) = 832
fstat(18, {st_mode=S_IFREG|0755, st_size=578059, ...}) = 0
mmap(NULL, 2508456, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 18, 0) = 0x7f7c0e459000
mprotect(0x7f7c0e4b7000, 2093056, PROT_NONE) = 0
mmap(0x7f7c0e6b6000, 28672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 18, 0x5d000) = 0x7f7c0e6b6000
mmap(0x7f7c0e6bd000, 1704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f7c0e6bd000
close(18)                               = 0
```

Note that it is loading foundation.so via synergia-pre3, but then it is loading libsynergia_foundation.so from 2.7.10. 

I looked at RUNPATH (RPATH) of the *.so files, and they don't point to 2.7.10 so not sure where that's coming from. It might have to do some symlinks to 2.7.10 pyenv, but it doesn't quite make sense, because this doesn't help:

```sh
```

**Comment by robnagler** [comment]
Setting a separate pyenv-virtualenv (pre3) with pyenv global (2.7.9) seems to work. I think the model of using the pyenv globally may be problematic.

I also think synergia needs to install in lib/synergia not in lib/ in the virtualenv. This was lazy code of mine to fix the install. I'll build new images with these ideas, and see what happens.

**Comment by robnagler** [comment]
Just FYI. I've been getting strange download issues. (I think @elventear is having similar problems.) This is causing significant delays on debugging, since building radiasoft/beamsim takes hours...  Building synergia takes a least a half hour.

**Comment by robnagler** [comment]
Building clean virtualenvs works. The new structure is 2.7.10 is just a pyenv. py2 and synergia-pre3 are virtualenvs built off 2.7.10. 

Synergia is now installed in <venv>/lib/synergia/*. 

The SYNERGIA2DIR and variables are set by a pyenv exec hook. However, when jupyter starts, it sets the variables via the exec hook so they are inherited by terminals and notebooks, because they are children of the jupyter kernel. This shouldn't be a problem if you use `pyenv activate`.

This code tests for a pre3 feature:

```python
import synergia; print bool(synergia.foundation.foundation.Reference_particle.get_mass)
```

**Comment by robnagler** [comment]
@ncook82 and @cchall please try out the jupyter server. It works for me.

**Comment by cchall** [comment]
Appears to be working for me. I can now import synergia while using the
synergia-pre3 kernel.
