### ISSUE TITLE
Define the environment variable RPN_DEFNS on Jupyter

### ISSUE THREAD

**Issue by cchall** [radiasoft/devops#63]
For elegant to run there should be an RPN_DEFNS environment variable pointing to the defns.rpn file. This is easy to do but would probably be nice if it were set by default for any new Jupyter users so they don't have to mess with it.

**Comment by robnagler** [comment]
@cchall what should the value be? I normally set it to "/dev/null", but that's just to avoid the error. Do you have std set of defs?

**Comment by cchall** [comment]
The RPN_DEFNS variable should point to the location of defns.rpn file. The
defns.rpn file can be downloaded from:
http://www.aps.anl.gov/Accelerator_Systems_Division/Accelerator_Operations_Physics/software.shtml#elegant
(it's a separate download from the elegant source).

**Comment by robnagler** [comment]
Sorry, I was under the impression that file might be customized by the user. We'll add it to the environment. @elventear there's a copy in sirepo. Probably should be done [like synergia](https://github.com/radiasoft/containers/blob/5db92571902b8d7eb633a4febcb43587605f1ae1/radiasoft/beamsim/codes/synergia.sh#L130).

**Comment by elventear** [comment]
Fixed by radiasoft/containers@41fee6a.

**Comment by cchall** [comment]
@robnagler 
It appears that the RPN_DEFNS is no longer being set again. Possibly after the recent Jupyter upgrade?

**Comment by robnagler** [comment]
`/usr/share/doc/elegant/defns.rpn` is missing. $RPN_DEFNS is defined in py2 and py3 kernels and terminal environments.

**Comment by robnagler** [comment]
I'll rebuild the beamsim containers
