### ISSUE TITLE
Synergia ImportError on Jupyter Server

### ISSUE THREAD

**Issue by cchall** [radiasoft/devops#68]
Trying to import the synergia module in an IPython notebook on the Jupyter server currently gives an ImportError.
Importing works when using an IPython shell.
Could be due to notebooks running on the 'jupyter' pyenv.

**Comment by elventear** [comment]
@cchall there are three Kernels (environments) under Jupyter:

- Python 2
- Python 2 synergia-pre3
- Python 3

Right now synergia is only available on the second, AFAIK. Python 3 exists because a recent upgrade to Jupyter forced us to use Python 3, but it does not come with any scientific codes pre-loaded. 

Which one are you trying to use with Synergia?

**Comment by cchall** [comment]
@elventear I'm currently using the Python 2 kernel.

My understanding was that there should be one environment with the 'standard' development branch of Synergia installed (this is what we've used in the past). A new environment (Python 2 synergia-pre3) was added to test the synergia-pre3 branch that has not been rolled out for official release and is currently somewhat unstable.

**Comment by elventear** [comment]
Synergia is installed and accessed through the `PYTHONPATH` which is set to `/home/vagrant/.pyenv/versions/jupyter/lib/synergia`. For some reason it doesn't seem to work within the Jupyter notebook, I will have to investigate more. 

I find it weird that they root synergia python mode installs actually to this path `/home/vagrant/.pyenv/versions/py2/lib/synergia/synergia/__init__.pyc`; thus the necessity of the `PYTHONPATH`.

@robnagler can you shed some light on this issue?

**Comment by elventear** [comment]
I see the issue now. The `PYTHONPATH` is being set by `penv` once when Jupyter starts, since Jupyter runs only with Python 3. The other Kernels will only inherit that setting.

**Comment by robnagler** [comment]
I thought we had a fix for that with the kernel config.

**Comment by robnagler** [comment]
It would be ideal also if we didn't show the Python 3 environment, because none of the beamsim codes are installed in py3.
