### ISSUE TITLE
installing rswarp on jupyter server

### ISSUE THREAD

**Issue by cchall** [radiasoft/devops#72]
Whenever I restart my instance of the jupyter server the rswarp module can no longer be found and needs to be reinstalled.

This does not seem to be occurring for others such as rssynergia.

**Comment by elventear** [comment]
@cchall `rswarp`should be installed now. Please try again.

**Comment by cchall** [comment]
Upon restarting my container rswarp still is not installed when I try to import it in python or ipython.
