### ISSUE TITLE
Add load monitor on jupyterhub

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#76]
Log cpu use. Could be simple script or maybe a tool.

**Comment by elventear** [comment]
[Vector](http://vectoross.io) provides a nice dashboard for realtime inspection. Does not have any alarming features.

**Comment by robnagler** [comment]
Vector no longer exists(?). We have a simple text file. Bigger problem is an allocation manager.

**Comment by elventear** [comment]
https://github.com/Netflix/vector

**Comment by robnagler** [comment]
thanks @elventear!
