### ISSUE TITLE
Push radiasoft/sirepo:20160314.172251 on alpha to beta

### ISSUE THREAD

**Issue by robnagler** [radiasoft/devops#8]
@mrakitin please verify alpha works to your satisfaction. We'll push to beta once you give ok.

**Comment by mrakitin** [comment]
Hi @robnagler, alpha looks good for me. I will be updating double-slit examples soon, as well as be adding crystal element, but we can make another release for these changes.

By the way, are you sure the version on alpha is 20160314.172251? I see this info in the source of the main page:
```js
      var SIREPO_APP_VERSION = '20160308';
```

**Comment by robnagler** [comment]
>
> Hi @robnagler <https://github.com/robnagler>, alpha looks good for me. I
> will be updating double-slit examples soon, as well as be adding crystal
> element, but we can make another release for these changes.
>

Great. I'll push to beta.

> By the way, are you sure the version on alpha is 20160314.172251? I see
> this info in the source of the main page:
>
>       var SIREPO_APP_VERSION = '20160308';
>
>
> That's the app version. The docker image build version is  20160314.172251.

**Comment by robnagler** [comment]
Pushed to beta
