### ISSUE TITLE
Rebuild Synergia on jupyter with fixed dipole feature

### ISSUE THREAD

**Issue by ncook882** [radiasoft/devops#88]
We have a temporary fix to remove the unwanted dipole fringe field effects in Synergia. Please update the build in Jupyter as soon as possible. The fix is as follows:

1. Change line 55 in build/chef-libs/beamline/include/Edge.h from
#define NO_FIXED_ENTRY_ANGLE true
to
#define NO_FIXED_ENTRY_ANGLE false

2. Rebuild and install in the chef-libs directory.

**Comment by robnagler** [comment]
This isn't checked in?

**Comment by ncook882** [comment]
No it's not currently a part of the Synergia source code, if that's what you mean. It needs to be added in by hand to the local system files.

**Comment by robnagler** [comment]
Is this for both devel and pre3?

**Comment by bruhwile** [comment]
Please put this issue on hold until further notice. I'll offer guidance
ASAP.

**Comment by ncook882** [comment]
Closed via recent update. See #92

**Comment by ncook882** [comment]
Closed via recent update. See #92
