### ISSUE TITLE
build Warp/PICSAR on Edison at NERSC

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/devops#95]
This is important but is not funded by any active projects, so charge time to Science Support or Tech Support.

Warp can use a new highly-optimized physics kernel called PICSAR. The primary goal is to build it on Cori, but the first step is to get it working on Edison.

The Warp source is here (as we all know):
https://bitbucket.org/berkeleylab/warp

The PICSAR home page is here:
https://picsar.net/

The Bitbucket repository is not yet open (will be soon, I hear), but if you send them your Bitbucket username, then they will give you read access.

**Comment by bruhwiler** [comment]
I've requested read access to PICSAR on Bitbucket.

**Comment by robnagler** [comment]
I think we are in good shape. If you want more work, LMK.
